apiVersion: batch/v1
kind: Job
metadata:
  name: digiclk-job
spec:
  template:
    spec:
      containers:
      - name: digiclk-job
        image: yash5090/digiclk:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
