apiVersion: apps/v1
kind: Deployment
metadata:
  name: digiclk-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: digiclk
  template:
    metadata:
      labels:
        app: digiclk
    spec:
      containers:
        - name: digiclk
          image: yash5090/digiclk:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
